// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-xopenasipbase -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg | FileCheck %s

#include <stdint.h>
#include <riscv_openasip_base.h>

// CHECK-LABEL: @test_xopenasipbase_openasip_base_max(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ELT_MAX_I:%.*]] = call i32 @llvm.riscv.xopenasipbase.openasip.base.max(i32 [[A:%.*]], i32 [[B:%.*]])
// CHECK-NEXT:    ret i32 [[ELT_MAX_I]]
//
int test_xopenasipbase_openasip_base_max(int32_t a, int32_t b) {
  return __riscv_xopenasipbase_openasip_base_max(a, b);
}

// CHECK-LABEL: @test_xopenasipbase_openasip_base_maxu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ELT_MAXU_I:%.*]] = call i32 @llvm.riscv.xopenasipbase.openasip.base.maxu(i32 [[A:%.*]], i32 [[B:%.*]])
// CHECK-NEXT:    ret i32 [[ELT_MAXU_I]]
//
int test_xopenasipbase_openasip_base_maxu(uint32_t a, uint32_t b) {
  return __riscv_xopenasipbase_openasip_base_maxu(a, b);
}
